config/routes.rb
Rails.application.routes.draw do
  root "receipts#index"

  resources :currency_rates, only: :index

  resources :receipts, except: %i[edit update] do
    member { get :export }
    collection { get :insights }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  scope :group_hourly, -> { group("TO_CHAR(created_at, 'yyyy-mm-dd HH:MM')") }
end

app/models/concerns/deletable.rb
module Deletable
  extend ::ActiveSupport::Concern

  included do
    scope :not_deleted, -> { where(deleted_at: nil) }

    def soft_deleted?
      try(:deleted_at).present?
    end

    def soft_delete!
      raise "Unable to soft delete record" unless respond_to? :deleted_at=

      @deleting_at = Time.now

      try(:deleted_at=, @deleting_at)
      save(validate: false)

      self
    end
  end
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  include Deletable

  has_many :receipt_items

  accepts_nested_attributes_for :receipt_items,
                                reject_if: proc { |item| item[:description].blank? }

  validates :amount, :tax_amount, presence: true

  enum default_currency: ::Currency.all
end

app/models/receipt_item.rb
class ReceiptItem < ApplicationRecord
  belongs_to :receipt

  scope :count_by_receipt, -> { group(:receipt_id).order(:receipt_id).count }

  validates :amount, :tax_amount, :quantity, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/currency_rates_controller.rb
class CurrencyRatesController < ApplicationController
  def index
    meta = ::Currency.symbols.transform_keys(&:upcase)
    data = ::GetConversionRatesService.execute

    render json: { success: true, meta: meta, data: data }
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: %i[show edit update destroy export]

  def index
    @q = Receipt.ransack(params[:q])
    @pagy, @receipts = pagy ReceiptsListQuery.query(relation: @q.result)
  end

  def insights
    @receipts_hourly = Receipt.group_hourly.count
    @receipts_items = ReceiptItem.count_by_receipt.map { |k, v| ["Receipt ##{k}", v] }
  end

  def show
    @default_currency = ::Currency.default_formatted
    @rates = ::Currency.all_formatted
  end

  def new
    @receipt = Receipt.new
    10.times { @receipt.receipt_items.build }
    @items = @receipt.receipt_items.to_a
  end

  def create
    @receipt =
      ::GenerateReceiptService.execute(items: receipt_params[:receipt_items_attributes])

    if @receipt
      redirect_to receipt_url(@receipt), notice: "Receipt was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @receipt.soft_delete!

    redirect_to receipts_url, notice: "Receipt was successfully destroyed."
  end

  def export
    send_data render_to_string(
                template: "receipts/export",
                layout: false,
                locals: {
                  receipt: @receipt
                }
              ),
              filename: "Receipt ##{@receipt.id}.txt",
              type: "text/plain"
  end

  private

  def set_receipt
    @receipt = Receipt.not_deleted.find(params[:id])
  end

  def receipt_params
    params.require(:receipt).permit(
      receipt_items_attributes: %i[amount quantity description]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  ::Pagy::DEFAULT[:items] = 5
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
  def monetize(amount, currency = ::Currency.default)
    ::Money.from_cents(amount, currency.to_s.upcase).format
  end
end

app/views/application/_navbar.html.erb
<nav class="border-gray-200 px-2 sm:px-4 py-2.5 bg-gray-900 w-full">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="/" class="flex items-center">
        <img id="logo" src="/taxy-logo.png" height="500" class="mr-3 h-6 sm:h-9" alt="Taxy Logo" />
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm  rounded-lg md:hidden focus:outline-none focus:ring-2  text-gray-400 hover:bg-gray-700 focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border  md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-gray-900 border-gray-700">
        <li>
          <%= link_to 'Receipts', receipts_path, class: "block py-2 pr-4 pl-3 text-gray-300 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 text-gray-400 md:hover:text-white hover:bg-gray-700 hover:text-white md:hover:bg-transparent" %>
        </li>
        <li>
          <%= link_to 'New Receipt', new_receipt_path, class: "block py-2 pr-4 pl-3 text-gray-300 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 text-gray-400 md:hover:text-white hover:bg-gray-700 hover:text-white md:hover:bg-transparent"%>
        </li>
        <li>
          <%= link_to 'Insights', insights_receipts_path, class: "block py-2 pr-4 pl-3 text-gray-300 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 text-gray-400 md:hover:text-white hover:bg-gray-700 hover:text-white md:hover:bg-transparent"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taxy - Sales Tax Calculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'navbar' %>

    <main class="w-full mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/receipts/_form.html.erb
<%= form_for(@receipt, class: "mx-auto") do |form| %>
  <% if receipt.errors.any? %>
    <div
      id="error_explanation"
      class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3"
    >
      <h2>
        <%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:
      </h2>

      <ul>
        <% receipt.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="flex justify-center my-6">
    <table class="table-auto w-2/3">
      <thead>
        <tr>
          <th>Quantity</th>
          <th>Description</th>
          <th>Shelf Price</th>
        </tr>
      </thead>
      <tbody>
        <% row = 0 %>
        <%= form.fields_for :receipt_items do |items_form| %>
          <tr class="w-full">
            <td class="w-1/4 pr-5">
              <%= items_form.number_field :quantity,
                                            value: 1,
                                            min: 1,
                                            class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              %>
            </td>
            <td class="w-2/4">
              <%= items_form.text_field :description,
                                          required: row.zero?,
                                          class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              %>
            </td>
            <td class="w-1/4 pl-5">
              <%= items_form.number_field :amount,
                                            step: 0.01,
                                            value: number_to_currency(0.to_f, delimiter: '', unit: ''),
                                            class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
              %>
            </td>
          </tr>

          <% row += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="flex justify-end">
    <%= link_to 'See Receipts',
              receipts_path,
              class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium mr-5"
            %>

    <%= form.submit 'Generate Receipt',
                    class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"
                  %>
  </div>

<% end %>

app/views/receipts/_receipt.html.erb
<div id="<%= dom_id receipt %>" class="receipt">
  <div class="my-5">
    <span>
      <strong class="inline-block font-bold mb-1">Total:</strong>
      <p class="price inline-block" data-base-price="<%= receipt.amount %>">
        <%= monetize receipt.amount %>
      </p>
    </span>

    <span class="ml-4">
      <strong class="inline-block font-bold mb-1">Tax:</strong>
      <p class="price inline-block" data-base-price="<%= receipt.tax_amount %>">
        <%= monetize receipt.tax_amount %>
      </p>
    </span>
  </div>

  <div class="flex justify-end items-center">
    <span class="font-sans font-light">Displaying prices in:</span>
    <span class="ml-4">
      <%= select_tag :selected_currency,
                     options_for_select(@rates, @default_currency),
                     id: 'currency-selector',
                     class: 'p-2 border rounded'
                    %>
    </span>
  </div>

  <div class="flex justify-center my-6">
    <table class="table-auto w-full">
      <thead class="shadow border-slate-50">
        <tr class="text-left">
          <th class="p-5">Quantity</th>
          <th class="p-5">Description</th>
          <th class="p-5">Amount</th>
          <th class="p-5">Tax</th>
        </tr>
      </thead>
      <tbody>
        <% row = 1 %>
        <% receipt.receipt_items.each do |item| %>
          <tr class="w-full text-left hover:bg-slate-50 shadow">
            <td class="w-1/4 pr-5">
              <%= content_tag :p,
                              item.quantity,
                              class: "block rounded outline-none px-3 py-2 mt-2 w-full" %>
            </td>
            <td class="w-2/4">
              <%= content_tag :p,
                              item.description,
                              class: "block rounded outline-none px-3 py-2 mt-2 w-full" %>
            </td>
            <td nowrap class="w-1/4 pl-5">
              <%= content_tag :p,
                              monetize(item.amount),
                              data: { base_price: item.amount },
                              class: "price block rounded outline-none px-3 py-2 mt-2 w-full" %>
            </td>
            <td nowrap class="w-1/4 pl-5">
              <%= content_tag :p,
                              monetize(item.tax_amount),
                              data: { base_price: item.tax_amount },
                              class: "price block rounded outline-none px-3 py-2 mt-2 w-full" %>
            </td>
          </tr>

          <% row += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/receipts/export.html.erb
********************************************************************************

                                    Taxy
                            Sales Tax Calculator

********************************************************************************

Receipt #<%= receipt.id %>


Total Amount <%= monetize receipt.amount %>
Total Tax <%= monetize receipt.tax_amount %>

--------------------------------------------------------------------------------

Receipt Items:

<% receipt.receipt_items.each_with_index do |item, index| %>

Item #<%= index + 1%>
  - Description: <%= item.description %>
  - Quantity: <%= item.quantity %>
  - Shelf Price: <%= monetize item.amount %>
  - Tax Amount: <%= monetize item.tax_amount %>

<% end %>

--------------------------------------------------------------------------------

Generated at <%= receipt.created_at.to_formatted_s(:long_ordinal) %>
Downloaded at <%= Time.now.to_formatted_s(:long_ordinal) %>

app/views/receipts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Receipts</h1>

    <%= search_form_for @q do |f| %>
      <%= f.search_field :receipt_items_description_i_cont,
        placeholder: 'Search by items descriptions...',
        class: 'w-72 inline-block border px-3 py-2 rounded outline-none placeholder-slate-300' %>

      <%= f.submit 'Search',
        class: 'inline-block rounded-lg px-3 py-2 bg-gray-400 hover:bg-gray-600 hover:cursor-pointer text-white font-medium' %>
    <% end %>

    <%= link_to 'New Receipt', new_receipt_path, class: "w-1/6 text-center rounded-lg py-3 bg-blue-400 hover:bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="receipts" class="mx-auto mt-12">
    <% if @receipts.count.zero? %>
      <p class="py-2 px-3 ml-5 rounded text-gray-500 text-center inline-block">Looks like you have no receipts yet</p>
    <% else %>
      <% @receipts.each do |receipt| %>
        <div class="flex justify-between items-center hover:bg-slate-50 p-5">
          <div class="my-5 mx-10">
            <span>
              <strong class="inline-block font-medium mb-1 mr-2">Total:</strong>
              <%= monetize receipt.amount %>
            </span>

            <span class="ml-20">
              <strong class="inline-block font-medium mb-1 mr-2">Tax:</strong>
              <%= monetize receipt.tax_amount %>
            </span>
          </div>

          <div>
            <%= link_to "See Details",
                        receipt,
                        class: "rounded-lg py-3 px-5 bg-gray-100 font-medium"
                      %>
          </div>
        </div>
      <% end %>

      <%== pagy_nav(@pagy) %>
    <% end %>
  </div>
</div>

app/views/receipts/insights.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Insights</h1>
  </div>

  <div id="insights" class="mx-auto mt-12">
    <div class="my-12">
      <p class="ml-5 py-5 text-slate-500 font-medium">Total Receipts created Hourly</p>
      <%= area_chart @receipts_hourly %>
    </div>

    <div class="my-12">
      <p class="ml-5 py-5 text-slate-500 font-medium">Total Items by Receipt</p>
      <%= bar_chart @receipts_items %>
    </div>
  </div>
</div>

app/views/receipts/new.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl">Item Details</h1>

  <%= render "form", receipt: @receipt %>
</div>

app/views/receipts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="flex justify-between w-full">
      <h1 class="font-bold text-4xl">Receipt</h1>
      <div class="flex">
        <%= link_to 'See Receipts', receipts_path, class: "block ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

        <%= link_to 'Export', export_receipt_path(@receipt), target: "_blank", class: "block ml-2 rounded-lg py-3 px-5 bg-blue-50 inline-block font-medium" %>

        <%= button_to 'Delete this Receipt',
                      receipt_path(@receipt),
                      method: :delete,
                      class: "block ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium bg-red-100"
        %>
      </div>
    </div>

    <%= render @receipt %>
  </div>
</div>